// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBCH3SHe9r7WI7c7MMTo7AjCHyrIMowQMA',
//     appId: '1:810306393389:web:94235bd490963d1e0aafa4',
//     messagingSenderId: '810306393389',
//     projectId: 'puchnotification-4c2ed',
//     authDomain: 'puchnotification-4c2ed.firebaseapp.com',
//     storageBucket: 'puchnotification-4c2ed.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyASv35c1g1HE5wTSNv-e7XAqZr4K6QxWVs',
//     appId: '1:810306393389:android:f9805af287187b8f0aafa4',
//     messagingSenderId: '810306393389',
//     projectId: 'puchnotification-4c2ed',
//     storageBucket: 'puchnotification-4c2ed.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAG1K8XLcBwcolFm6poqly5FnlXoGrjzlo',
//     appId: '1:810306393389:ios:5171160e2f61415f0aafa4',
//     messagingSenderId: '810306393389',
//     projectId: 'puchnotification-4c2ed',
//     storageBucket: 'puchnotification-4c2ed.appspot.com',
//     iosBundleId: 'com.example.pushnotifications',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAG1K8XLcBwcolFm6poqly5FnlXoGrjzlo',
//     appId: '1:810306393389:ios:27d9e2fa5e15a1040aafa4',
//     messagingSenderId: '810306393389',
//     projectId: 'puchnotification-4c2ed',
//     storageBucket: 'puchnotification-4c2ed.appspot.com',
//     iosBundleId: 'com.example.pushnotifications.RunnerTests',
//   );
// }
